import React, { FormEvent, useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";

type UserRole = "owner" | "editor" | "viewer";
type Page = "home" | "inventory" | "containers" | "assets" | "tasks" | "plans" | "targets" | "guidance" | "household" | "access";
type SystemInfo = { name: string; version: string; environment: string; api_version: string; server_id?: string };
type User = { id: string; username: string; role: UserRole; created_at: string; disabled_at: string | null };
type AuthStatus = { setup_required: boolean; authenticated: boolean; user: User | null };
type Household = { id: string; name: string; revision: number };
type HouseholdProfile = { household_id: string; country_code: string | null; adults: number; children: number; pets: number; preparedness_days: number; revision: number };
type InventoryItem = { id: string; household_id: string; name: string; category: string; item_type: string; quantity: number; unit: string; expires_at: string | null; container_id: string | null; revision: number };
type Container = { id: string; household_id: string; name: string; container_type: string; location: string | null; description: string | null; next_check_at: string | null; revision: number };
type Asset = { id: string; household_id: string; name: string; asset_type: string; location: string | null; description: string | null; instructions: string | null; next_check_at: string | null; revision: number };
type Task = { id: string; household_id: string; name: string; task_kind: string; category: string | null; linked_item_id: string | null; linked_container_id: string | null; linked_asset_id: string | null; recurrence_type: string; recurrence_interval: number; reschedule_mode: string; last_completed_at: string | null; next_due_at: string | null; reminder_before_days: number; enabled: boolean; completion_count: number; revision: number };
type Plan = { id: string; household_id: string; name: string; plan_type: string; description: string | null; meeting_point: string | null; enabled: boolean; checklist: Array<{ id: string; label: string; completed: boolean }>; review_interval_months: number; next_review_at: string | null; revision: number };
type Target = { id: string; household_id: string; name: string; category: string | null; target_type: string; unit: string | null; minimum_value: number | null; target_value: number | null; current_value: number | null; requirements: Array<{ id: string; label: string; description?: string | null; required?: boolean }>; completed_requirement_ids: string[]; priority: string; origin: string; enabled: boolean; revision: number };
type Guidance = { profile: { id: string; title: string; authority: string; disclaimer?: string }; household: HouseholdProfile; recommendations: Array<{ id: string; title: string; category?: string; target_type: string; priority: string; applicable?: boolean; advisory_note?: string; calculated?: { minimum_value?: number; target_value?: number; unit?: string; requirements?: Array<{ id: string; label: string }> } }> };
type Readiness = { status: string; score: number | null; inventory_items: number; targets: { status: string; total: number; met: number; below_target: number; below_minimum: number; unknown: number }; target_evaluations: Array<{ target_id: string; name: string; status: string; progress_label: string | null }>; tasks: { status: string; total: number; overdue: number; due: number; upcoming: number; ok: number; unscheduled: number }; task_rows: Array<{ id: string; name: string; status: string; next_due_at: string | null }> };
type ApiErrorBody = { error?: { code?: string; message?: string } };

async function request<T>(url: string, init?: RequestInit): Promise<T> {
  const response = await fetch(url, { credentials: "same-origin", headers: { "Content-Type": "application/json", ...(init?.headers ?? {}) }, ...init });
  if (!response.ok) {
    const body = (await response.json().catch(() => ({}))) as ApiErrorBody;
    throw new Error(body.error?.message ?? `${response.status} ${response.statusText}`);
  }
  if (response.status === 204) return undefined as T;
  return response.json() as Promise<T>;
}

const PAGE_NAMES: Record<Page, string> = { home: "Home", inventory: "Inventory", containers: "Containers", assets: "Assets", tasks: "Tasks", plans: "Plans", targets: "Targets", guidance: "Guidance", household: "Household", access: "Access Control" };
function pageFromHash(): Page { const value = window.location.hash.replace(/^#\/?/, "") as Page; return value in PAGE_NAMES ? value : "home"; }
function label(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (m) => m.toUpperCase()); }
function statusClass(value?: string | null) { return `chip ${value ?? "neutral"}`; }

function AuthCard({ setupRequired, onAuthenticated }: { setupRequired: boolean; onAuthenticated: () => Promise<void> }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); const form = new FormData(event.currentTarget);
    const password = String(form.get("password") ?? ""); const confirmPassword = String(form.get("confirmPassword") ?? "");
    if (setupRequired && password !== confirmPassword) { setError("Passwords do not match."); setBusy(false); return; }
    try { await request(setupRequired ? "/api/v1/auth/setup" : "/api/v1/auth/login", { method: "POST", body: JSON.stringify({ username: String(form.get("username") ?? "").trim(), password }) }); await onAuthenticated(); }
    catch (err) { setError(err instanceof Error ? err.message : "Authentication failed"); } finally { setBusy(false); }
  }
  return <section className="auth-wrap"><div className="card auth-card"><div className="auth-logo">HP</div><span className="eyebrow">HOME PREP SERVER</span><h2>{setupRequired ? "Create your owner account" : "Welcome back"}</h2><p>Your preparedness data stays on the HomePrep Server you control.</p>{error && <div className="error">{error}</div>}<form className="form" onSubmit={submit}><label className="field"><span>Username</span><input name="username" required minLength={3} autoFocus /></label><label className="field"><span>Password</span><input name="password" type="password" required minLength={setupRequired ? 12 : 1} /></label>{setupRequired && <label className="field"><span>Confirm password</span><input name="confirmPassword" type="password" required minLength={12} /></label>}<button disabled={busy}>{busy ? "Please wait…" : setupRequired ? "Create owner" : "Sign in"}</button></form></div></section>;
}

function App() {
  const [page, setPage] = useState<Page>(pageFromHash()); const [system, setSystem] = useState<SystemInfo | null>(null); const [ready, setReady] = useState(false); const [auth, setAuth] = useState<AuthStatus | null>(null); const [households, setHouseholds] = useState<Household[]>([]); const [householdId, setHouseholdId] = useState(""); const [profile, setProfile] = useState<HouseholdProfile | null>(null); const [inventory, setInventory] = useState<InventoryItem[]>([]); const [containers, setContainers] = useState<Container[]>([]); const [assets, setAssets] = useState<Asset[]>([]); const [tasks, setTasks] = useState<Task[]>([]); const [plans, setPlans] = useState<Plan[]>([]); const [targets, setTargets] = useState<Target[]>([]); const [guidance, setGuidance] = useState<Guidance | null>(null); const [readiness, setReadiness] = useState<Readiness | null>(null); const [users, setUsers] = useState<User[]>([]); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const role = auth?.user?.role ?? "viewer"; const canWrite = role === "owner" || role === "editor"; const isOwner = role === "owner"; const activeHousehold = useMemo(() => households.find((h) => h.id === householdId) ?? null, [households, householdId]);

  useEffect(() => { const handler = () => setPage(pageFromHash()); window.addEventListener("hashchange", handler); return () => window.removeEventListener("hashchange", handler); }, []);
  function navigate(next: Page) { window.location.hash = next === "home" ? "/" : `/${next}`; setPage(next); setError(""); }
  function fail(err: unknown, fallback: string) { setError(err instanceof Error ? err.message : fallback); }

  async function loadDomainData(id: string, currentRole: UserRole) {
    const [inv, cont, ass, taskList, planList, targetList] = await Promise.all([request<InventoryItem[]>(`/api/v1/inventory?household_id=${id}`), request<Container[]>(`/api/v1/containers?household_id=${id}`), request<Asset[]>(`/api/v1/assets?household_id=${id}`), request<Task[]>(`/api/v1/tasks?household_id=${id}`), request<Plan[]>(`/api/v1/plans?household_id=${id}`), request<Target[]>(`/api/v1/targets?household_id=${id}`)]);
    setInventory(inv); setContainers(cont); setAssets(ass); setTasks(taskList); setPlans(planList); setTargets(targetList);
    const [profileResult, readinessResult] = await Promise.all([request<HouseholdProfile>(`/api/v1/household-profile/${id}`).catch(() => null), request<Readiness>(`/api/v1/readiness/${id}`).catch(() => null)]);
    setProfile(profileResult); setReadiness(readinessResult);
    if (profileResult) setGuidance(await request<Guidance>(`/api/v1/guidance/${id}`).catch(() => null)); else setGuidance(null);
    if (currentRole === "owner") setUsers(await request<User[]>("/api/v1/users")); else setUsers([]);
  }

  async function bootstrap() {
    setLoading(true); setError("");
    try {
      const [info, readinessState, authStatus] = await Promise.all([request<SystemInfo>("/api/v1/system/info"), request<{ status: string }>("/readyz"), request<AuthStatus>("/api/v1/auth/status")]);
      setSystem(info); setReady(readinessState.status === "ready"); setAuth(authStatus);
      if (authStatus.authenticated && authStatus.user) { const householdList = await request<Household[]>("/api/v1/households"); setHouseholds(householdList); const selected = householdList[0]?.id ?? ""; setHouseholdId(selected); if (selected) await loadDomainData(selected, authStatus.user.role); }
      else { setHouseholds([]); setHouseholdId(""); }
    } catch (err) { fail(err, "Unable to connect to HomePrep Server"); } finally { setLoading(false); }
  }
  useEffect(() => { void bootstrap(); }, []);
  useEffect(() => { if (page === "access" && !isOwner && auth?.authenticated) navigate("home"); }, [page, isOwner, auth?.authenticated]);
  async function refresh() { if (householdId && auth?.user) await loadDomainData(householdId, auth.user.role); }

  async function createHousehold(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await request<Household>("/api/v1/households", { method: "POST", body: JSON.stringify({ name: String(form.get("name") ?? "").trim() }) }); await bootstrap(); navigate("household"); } catch (err) { fail(err, "Unable to create household"); } }
  async function saveProfile(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!householdId) return; const form = new FormData(event.currentTarget); try { await request(`/api/v1/household-profile/${householdId}`, { method: "PUT", body: JSON.stringify({ country_code: String(form.get("country_code") ?? "OTHER"), adults: Number(form.get("adults") ?? 1), children: Number(form.get("children") ?? 0), pets: Number(form.get("pets") ?? 0), preparedness_days: Number(form.get("preparedness_days") ?? 7), expected_revision: profile?.revision ?? null }) }); await refresh(); } catch (err) { fail(err, "Unable to save household profile"); } }
  async function createInventory(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!householdId || !canWrite) return; const formElement = event.currentTarget; const form = new FormData(formElement); try { await request("/api/v1/inventory", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? "").trim(), category: String(form.get("category") ?? "other"), item_type: "consumable", quantity: Number(form.get("quantity") ?? 1), unit: String(form.get("unit") ?? "pcs"), container_id: String(form.get("container_id") ?? "") || null }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add inventory item"); } }
  async function createContainer(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await request("/api/v1/containers", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? ""), container_type: String(form.get("container_type") ?? "other"), location: String(form.get("location") ?? "") || null }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add container"); } }
  async function createAsset(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await request("/api/v1/assets", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? ""), asset_type: String(form.get("asset_type") ?? "other"), location: String(form.get("location") ?? "") || null, instructions: String(form.get("instructions") ?? "") || null }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add asset"); } }
  async function createTask(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const kind = String(form.get("task_kind") ?? "general"); try { await request("/api/v1/tasks", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? ""), task_kind: kind, linked_item_id: kind === "inspection" ? String(form.get("linked_id") ?? "") || null : null, linked_container_id: kind === "container_inspection" ? String(form.get("linked_id") ?? "") || null : null, linked_asset_id: kind === "asset_inspection" ? String(form.get("linked_id") ?? "") || null : null, recurrence_type: String(form.get("recurrence_type") ?? "months"), recurrence_interval: Number(form.get("recurrence_interval") ?? 1), next_due_at: String(form.get("next_due_at") ?? "") || null, reminder_before_days: Number(form.get("reminder_before_days") ?? 0) }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add task"); } }
  async function completeTask(task: Task) { try { await request(`/api/v1/tasks/${task.id}/complete`, { method: "POST", body: JSON.stringify({ expected_revision: task.revision }) }); await refresh(); } catch (err) { fail(err, "Unable to complete task"); } }
  async function createPlan(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const checklist = String(form.get("checklist") ?? "").split("\n").map((x) => x.trim()).filter(Boolean).map((x) => ({ label: x })); try { await request("/api/v1/plans", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? ""), plan_type: String(form.get("plan_type") ?? "other"), description: String(form.get("description") ?? "") || null, meeting_point: String(form.get("meeting_point") ?? "") || null, checklist, review_interval_months: Number(form.get("review_interval_months") ?? 0) }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add plan"); } }
  async function createTarget(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); const targetType = String(form.get("target_type") ?? "quantity"); const category = String(form.get("category") ?? "other"); try { await request("/api/v1/targets", { method: "POST", body: JSON.stringify({ household_id: householdId, name: String(form.get("name") ?? ""), category, target_type: targetType, matcher: ["quantity", "count"].includes(targetType) ? { category } : {}, unit: String(form.get("unit") ?? "") || null, minimum_value: String(form.get("minimum_value") ?? "") === "" ? null : Number(form.get("minimum_value")), target_value: String(form.get("target_value") ?? "") === "" ? null : Number(form.get("target_value")), priority: String(form.get("priority") ?? "normal") }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to add target"); } }
  async function toggleRequirement(target: Target, requirementId: string) { const completed = new Set(target.completed_requirement_ids); completed.has(requirementId) ? completed.delete(requirementId) : completed.add(requirementId); try { await request(`/api/v1/targets/${target.id}`, { method: "PATCH", body: JSON.stringify({ completed_requirement_ids: [...completed], expected_revision: target.revision }) }); await refresh(); } catch (err) { fail(err, "Unable to update target"); } }
  async function adoptRecommendation(id: string) { try { await request("/api/v1/guidance/adopt", { method: "POST", body: JSON.stringify({ household_id: householdId, recommendation_id: id }) }); await refresh(); } catch (err) { fail(err, "Unable to adopt recommendation"); } }
  async function remove(path: string, id: string, revision: number) { if (!confirm("Delete this HomePrep item?")) return; try { await request(`/api/v1/${path}/${id}?expected_revision=${revision}`, { method: "DELETE" }); await refresh(); } catch (err) { fail(err, "Unable to delete item"); } }

  async function createUser(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const formElement = event.currentTarget; const form = new FormData(formElement); try { await request("/api/v1/users", { method: "POST", body: JSON.stringify({ username: String(form.get("username") ?? ""), password: String(form.get("password") ?? ""), role: String(form.get("role") ?? "viewer") }) }); formElement.reset(); await refresh(); } catch (err) { fail(err, "Unable to create user"); } }
  async function updateUser(user: User, body: object) { try { await request(`/api/v1/users/${user.id}`, { method: "PATCH", body: JSON.stringify(body) }); await bootstrap(); } catch (err) { fail(err, "Unable to update user"); } }
  async function logout() { await request<void>("/api/v1/auth/logout", { method: "POST" }); navigate("home"); await bootstrap(); }

  if (loading && auth === null) return <div className="boot">Starting HomePrep…</div>;
  if (auth && !auth.authenticated) return <main className="shell login-shell"><header className="topbar"><div className="brandmark">HP</div><div><h1>HomePrep</h1><p>PREPARE • MONITOR • BE READY</p></div><div className={`status ${ready ? "online" : "offline"}`}><span />{ready ? "Server online" : "Server unavailable"}</div></header>{error && <div className="error">{error}</div>}<AuthCard setupRequired={auth.setup_required} onAuthenticated={bootstrap} /></main>;

  const navPages: Page[] = ["home", "inventory", "containers", "assets", "tasks", "plans", "targets", "guidance", "household"];
  const attention = [...(readiness?.task_rows.filter((t) => ["overdue", "due", "upcoming", "unscheduled"].includes(t.status)) ?? []), ...(readiness?.target_evaluations.filter((t) => t.status !== "met") ?? [])];
  return <main className="shell"><header className="topbar"><div className="brandmark">HP</div><div className="brandcopy"><h1>HomePrep</h1><p>PREPARE • MONITOR • BE READY</p></div><div className={`status ${ready ? "online" : "offline"}`}><span />{ready ? "Server online" : "Server unavailable"}</div><button className="secondary compact" onClick={() => void logout()}>Sign out</button></header>
    <nav className="app-nav">{navPages.map((p) => <button key={p} className={page === p ? "active" : ""} onClick={() => navigate(p)}>{PAGE_NAMES[p]}</button>)}{isOwner && <button className={page === "access" ? "active" : ""} onClick={() => navigate("access")}>Access Control</button>}</nav>
    {error && <div className="error">{error}</div>}

    {page === "home" && <><section className="hero card"><div><span className="eyebrow">HOUSEHOLD OVERVIEW</span><h2>{activeHousehold?.name ?? "Set up your household"}</h2><p>Your self-hosted preparedness command center. Data, users and security stay under your control.</p></div><div className="server-meta"><div><span>Version</span><strong>{system?.version ?? "—"}</strong></div><div><span>Role</span><strong>{role}</strong></div><div><span>Status</span><strong>{readiness?.status ?? "setup"}</strong></div></div></section><section className="metric-grid"><article className="metric-card card"><span>Readiness</span><strong>{readiness?.score == null ? "—" : `${readiness.score}%`}</strong><small>{readiness?.targets.total ?? 0} active targets</small></article><article className="metric-card card"><span>Inventory</span><strong>{inventory.length}</strong><small>Tracked supplies</small></article><article className="metric-card card"><span>Containers</span><strong>{containers.length}</strong><small>Storage locations</small></article><article className="metric-card card"><span>Attention</span><strong>{attention.length}</strong><small>Targets and tasks</small></article></section><section className="home-grid"><article className="card panel"><div className="section-title"><div><span className="eyebrow">READINESS</span><h3>Preparedness overview</h3></div></div><div className="readiness-placeholder"><div className={`gauge-ring score-${readiness?.status ?? "neutral"}`}><span>{readiness?.score == null ? "—" : readiness.score}</span></div><div><strong>{label(readiness?.status ?? "Set up targets")}</strong><p>{readiness ? `${readiness.targets.met} of ${readiness.targets.total} targets met. ${readiness.tasks.overdue} overdue tasks.` : "Complete the household wizard and adopt Guidance targets to activate readiness scoring."}</p></div></div></article><article className="card panel"><div className="section-title"><div><span className="eyebrow">NEXT ACTIONS</span><h3>Attention queue</h3></div></div>{attention.length ? <div className="entity-list">{attention.slice(0, 7).map((row: any) => <div className="mini-row" key={row.id ?? row.target_id}><span className={statusClass(row.status)}>{label(row.status)}</span><strong>{row.name}</strong></div>)}</div> : <div className="empty">No current attention items.</div>}</article></section></>}

    {page === "household" && <section className="card panel page-card"><div className="section-title"><div><span className="eyebrow">HOUSEHOLD WIZARD</span><h3>Household profile</h3><p className="section-copy">This profile drives country guidance, targets and readiness calculations.</p></div></div>{!activeHousehold && isOwner ? <form className="form form-narrow" onSubmit={createHousehold}><label className="field"><span>Household name</span><input name="name" required /></label><button>Create household</button></form> : activeHousehold ? <form className="form form-grid" onSubmit={saveProfile}><label className="field"><span>Country</span><select name="country_code" defaultValue={profile?.country_code ?? "OTHER"}><option value="SE">Sweden</option><option value="NO">Norway</option><option value="OTHER">Other / general</option></select></label><label className="field"><span>Adults</span><input name="adults" type="number" min="0" defaultValue={profile?.adults ?? 1} /></label><label className="field"><span>Children</span><input name="children" type="number" min="0" defaultValue={profile?.children ?? 0} /></label><label className="field"><span>Pets</span><input name="pets" type="number" min="0" defaultValue={profile?.pets ?? 0} /></label><label className="field"><span>Preparedness days</span><input name="preparedness_days" type="number" min="1" defaultValue={profile?.preparedness_days ?? 7} /></label>{canWrite && <button>Save household profile</button>}</form> : <div className="empty">An owner must create the household first.</div>}</section>}

    {page === "inventory" && <section className="card panel page-card"><PageTitle eyebrow="INVENTORY" title="Preparedness supplies" copy="Track what you have and where it is stored." refresh={refresh} /><EntityList empty="No inventory yet." rows={inventory.map((item) => ({ id: item.id, title: item.name, meta: `${label(item.category)} · ${item.quantity} ${item.unit}${item.container_id ? ` · ${containers.find((c) => c.id === item.container_id)?.name ?? "Container"}` : ""}`, revision: item.revision, path: "inventory" }))} canWrite={canWrite} remove={remove} />{canWrite && <form className="entity-create" onSubmit={createInventory}><input name="name" placeholder="Item name" required /><input name="quantity" type="number" min="0" step="0.1" defaultValue="1" required /><select name="unit" defaultValue="pcs"><option value="pcs">pcs</option><option value="liter">liter</option><option value="kilogram">kg</option></select><select name="category" defaultValue="other"><option value="food">Food</option><option value="water">Water</option><option value="medicine">Medicine</option><option value="power">Power</option><option value="lighting">Lighting</option><option value="other">Other</option></select><select name="container_id" defaultValue=""><option value="">No container</option>{containers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><button>Add item</button></form>}</section>}

    {page === "containers" && <section className="card panel page-card"><PageTitle eyebrow="CONTAINERS" title="Storage and kits" copy="Organize supplies into bags, crates, water containers and storage locations." refresh={refresh} /><EntityList empty="No containers yet." rows={containers.map((c) => ({ id: c.id, title: c.name, meta: `${label(c.container_type)}${c.location ? ` · ${c.location}` : ""} · ${inventory.filter((i) => i.container_id === c.id).length} items`, revision: c.revision, path: "containers" }))} canWrite={canWrite} remove={remove} />{canWrite && <form className="entity-create" onSubmit={createContainer}><input name="name" placeholder="Container name" required /><select name="container_type"><option value="bag">Bag</option><option value="box_crate">Box / crate</option><option value="water_container">Water container</option><option value="cabinet_storage">Cabinet / storage</option><option value="vehicle_storage">Vehicle storage</option><option value="other">Other</option></select><input name="location" placeholder="Location" /><button>Add container</button></form>}</section>}

    {page === "assets" && <section className="card panel page-card"><PageTitle eyebrow="ASSETS" title="Household preparedness assets" copy="Keep critical household infrastructure documented and inspectable." refresh={refresh} /><EntityList empty="No assets yet." rows={assets.map((a) => ({ id: a.id, title: a.name, meta: `${label(a.asset_type)}${a.location ? ` · ${a.location}` : ""}`, revision: a.revision, path: "assets" }))} canWrite={canWrite} remove={remove} />{canWrite && <form className="entity-create wide" onSubmit={createAsset}><input name="name" placeholder="Asset name" required /><select name="asset_type"><option value="water_shutoff">Water shutoff</option><option value="smoke_alarm">Smoke alarm</option><option value="fire_extinguisher">Fire extinguisher</option><option value="electrical_panel">Electrical panel</option><option value="generator">Generator</option><option value="floor_drain">Floor drain</option><option value="leak_sensor">Leak sensor</option><option value="other">Other</option></select><input name="location" placeholder="Location" /><input name="instructions" placeholder="Instructions" /><button>Add asset</button></form>}</section>}

    {page === "tasks" && <section className="card panel page-card"><PageTitle eyebrow="TASKS" title="Recurring checks" copy="Tasks are the authority for inspection schedules across inventory, containers and assets." refresh={refresh} /><div className="entity-list">{tasks.length === 0 && <div className="empty">No tasks yet.</div>}{tasks.map((task) => { const status = readiness?.task_rows.find((r) => r.id === task.id)?.status ?? "unscheduled"; return <article className="entity-row" key={task.id}><div><strong>{task.name}</strong><span>{label(task.task_kind)} · every {task.recurrence_interval} {task.recurrence_type} · {task.next_due_at ?? "unscheduled"}</span></div><span className={statusClass(status)}>{label(status)}</span>{canWrite && <div className="row-actions"><button className="secondary compact" onClick={() => void completeTask(task)}>Complete</button><button className="danger compact" onClick={() => void remove("tasks", task.id, task.revision)}>Delete</button></div>}</article>})}</div>{canWrite && <form className="entity-create wide" onSubmit={createTask}><input name="name" placeholder="Task name" required /><select name="task_kind"><option value="general">General</option><option value="inspection">Inventory inspection</option><option value="container_inspection">Container inspection</option><option value="asset_inspection">Asset inspection</option></select><select name="linked_id" defaultValue=""><option value="">No linked resource</option><optgroup label="Inventory">{inventory.map((i) => <option key={i.id} value={i.id}>{i.name}</option>)}</optgroup><optgroup label="Containers">{containers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</optgroup><optgroup label="Assets">{assets.map((a) => <option key={a.id} value={a.id}>{a.name}</option>)}</optgroup></select><input name="recurrence_interval" type="number" min="1" defaultValue="1" /><select name="recurrence_type"><option value="days">Days</option><option value="weeks">Weeks</option><option value="months">Months</option><option value="years">Years</option></select><input name="next_due_at" type="date" /><input name="reminder_before_days" type="number" min="0" defaultValue="0" /><button>Add task</button></form>}</section>}

    {page === "plans" && <section className="card panel page-card"><PageTitle eyebrow="PLANS" title="Preparedness plans" copy="Actionable household plans with checklists and review cycles." refresh={refresh} /><div className="card-grid">{plans.length === 0 && <div className="empty">No plans yet.</div>}{plans.map((plan) => <article className="sub-card" key={plan.id}><div className="section-title"><div><strong>{plan.name}</strong><span>{label(plan.plan_type)}</span></div>{canWrite && <button className="danger compact" onClick={() => void remove("plans", plan.id, plan.revision)}>Delete</button>}</div><p>{plan.description || "No description"}</p>{plan.meeting_point && <small>Meeting point: {plan.meeting_point}</small>}<div className="checklist">{plan.checklist.map((item) => <label key={item.id}><input type="checkbox" checked={item.completed} readOnly />{item.label}</label>)}</div></article>)}</div>{canWrite && <form className="form form-grid" onSubmit={createPlan}><input name="name" placeholder="Plan name" required /><select name="plan_type"><option value="fire">Fire</option><option value="flood">Flood</option><option value="evacuation">Evacuation</option><option value="power_outage">Power outage</option><option value="communication">Communication</option><option value="shelter">Shelter</option><option value="other">Other</option></select><input name="meeting_point" placeholder="Meeting point" /><input name="review_interval_months" type="number" min="0" defaultValue="6" /><textarea name="description" placeholder="Plan description" /><textarea name="checklist" placeholder={'Checklist, one line per step\nTurn off main water\nCollect go bags'} /><button>Add plan</button></form>}</section>}

    {page === "targets" && <section className="card panel page-card"><PageTitle eyebrow="TARGETS" title="Preparedness targets" copy="Turn recommendations and your own goals into measurable readiness." refresh={refresh} /><div className="card-grid">{targets.length === 0 && <div className="empty">No targets yet. Visit Guidance to adopt a recommended baseline.</div>}{targets.map((target) => { const evaluation = readiness?.target_evaluations.find((e) => e.target_id === target.id); return <article className="sub-card" key={target.id}><div className="section-title"><div><strong>{target.name}</strong><span>{label(target.category ?? target.target_type)} · {target.origin}</span></div><span className={statusClass(evaluation?.status)}>{label(evaluation?.status ?? "unknown")}</span></div><p>{evaluation?.progress_label ?? "Not evaluated"}</p>{target.requirements.length > 0 && <div className="checklist">{target.requirements.map((req) => <label key={req.id}><input type="checkbox" checked={target.completed_requirement_ids.includes(req.id)} disabled={!canWrite} onChange={() => void toggleRequirement(target, req.id)} />{req.label}</label>)}</div>}{canWrite && <button className="danger compact" onClick={() => void remove("targets", target.id, target.revision)}>Delete</button>}</article>})}</div>{canWrite && <form className="entity-create wide" onSubmit={createTarget}><input name="name" placeholder="Target name" required /><select name="target_type"><option value="quantity">Quantity</option><option value="count">Count</option><option value="coverage">Coverage</option></select><input name="category" placeholder="Category (water, food...)" required /><input name="unit" placeholder="Unit (liter, piece...)" /><input name="minimum_value" type="number" min="0" step="0.1" placeholder="Minimum" /><input name="target_value" type="number" min="0" step="0.1" placeholder="Target" /><select name="priority"><option value="normal">Normal</option><option value="high">High</option><option value="critical">Critical</option></select><button>Add target</button></form>}</section>}

    {page === "guidance" && <section className="card panel page-card"><PageTitle eyebrow="GUIDANCE" title={guidance?.profile.title ?? "Preparedness guidance"} copy={profile ? `${guidance?.profile.authority ?? "HomePrep"} · recommendations calculated for your household profile.` : "Complete the Household wizard to activate country-aware guidance."} refresh={refresh} />{guidance?.profile.disclaimer && <div className="info-box">{guidance.profile.disclaimer}</div>}<div className="card-grid">{guidance?.recommendations.filter((r) => r.applicable !== false).map((rec) => { const adopted = targets.some((t) => t.origin === "recommendation" && t.name === rec.title); return <article className="sub-card" key={rec.id}><div className="section-title"><div><span className="eyebrow">{label(rec.priority)}</span><strong>{rec.title}</strong></div><span className={statusClass(adopted ? "met" : "neutral")}>{adopted ? "Adopted" : label(rec.target_type)}</span></div>{rec.calculated?.target_value != null && <p className="big-value">{rec.calculated.target_value} {rec.calculated.unit}</p>}{rec.advisory_note && <p>{rec.advisory_note}</p>}{canWrite && !adopted && <button onClick={() => void adoptRecommendation(rec.id)}>Adopt target</button>}</article>})}</div></section>}

    {page === "access" && isOwner && <section className="card panel page-card"><PageTitle eyebrow="ACCESS CONTROL" title="Users and roles" copy="Human access for Web and future Android. Home Assistant credentials remain separate." refresh={refresh} /><div className="role-strip"><div><strong>Owner</strong><span>Full administration</span></div><div><strong>Editor</strong><span>Read/write preparedness data</span></div><div><strong>Viewer</strong><span>Read-only access</span></div></div><div className="user-list">{users.map((user) => <article className="user-row" key={user.id}><div><strong>{user.username}</strong><span>{user.disabled_at ? "Disabled" : "Active"}</span></div><select value={user.role} disabled={Boolean(user.disabled_at)} onChange={(event) => void updateUser(user, { role: event.target.value })}><option value="owner">Owner</option><option value="editor">Editor</option><option value="viewer">Viewer</option></select><button className="secondary compact" onClick={() => void updateUser(user, { disabled: !user.disabled_at })}>{user.disabled_at ? "Enable" : "Disable"}</button></article>)}</div><form className="user-create" onSubmit={createUser}><input name="username" placeholder="Username" minLength={3} required /><input name="password" type="password" placeholder="Password (12+ chars)" minLength={12} required /><select name="role" defaultValue="viewer"><option value="viewer">Viewer</option><option value="editor">Editor</option><option value="owner">Owner</option></select><button>Add user</button></form></section>}
    <footer><span>HomePrep Server {system?.version ?? ""} · {auth?.user?.username ?? ""} ({role})</span><span>Your preparedness. Your server. Your data.</span></footer></main>;
}

function PageTitle({ eyebrow, title, copy, refresh }: { eyebrow: string; title: string; copy: string; refresh: () => Promise<void> }) { return <div className="section-title"><div><span className="eyebrow">{eyebrow}</span><h3>{title}</h3><p className="section-copy">{copy}</p></div><button className="secondary" onClick={() => void refresh()}>Refresh</button></div>; }
function EntityList({ rows, empty, canWrite, remove }: { rows: Array<{ id: string; title: string; meta: string; revision: number; path: string }>; empty: string; canWrite: boolean; remove: (path: string, id: string, revision: number) => Promise<void> }) { return <div className="entity-list">{rows.length === 0 && <div className="empty">{empty}</div>}{rows.map((row) => <article className="entity-row" key={row.id}><div><strong>{row.title}</strong><span>{row.meta}</span></div>{canWrite && <button className="danger compact" onClick={() => void remove(row.path, row.id, row.revision)}>Delete</button>}</article>)}</div>; }

createRoot(document.getElementById("root")!).render(<React.StrictMode><App /></React.StrictMode>);
